#!/usr/bin/env ruby

CONFIG_SHOW_BUNDLER_UPDATE_WARNING = false
CONFIG_SHOW_BUNDLER_CONFIG_WARNING = false
CONFIG_SHOW_BUNDLER_CALLED_WARNING = false

require 'fileutils'

if File.exist?("/app/xtr-001")
  FileUtils.cp("/app/xtr-001", "/app/Gemfile")
else
  FileUtils.cp("/app/bhvr/directors/Gemfile.base", "/app/Gemfile")
end

if File.exist?("/app/xtr-002")
  FileUtils.cp("/app/xtr-002", "/app/Gemfile.lock")
else
  FileUtils.cp("/app/bhvr/directors/Gemfile.lock", "/app/Gemfile.lock")
end

if File.exist?("/app/xtr-003")
  FileUtils.cp("/app/xtr-003", "/app/Procfile")
else
  FileUtils.cp("/app/bhvr/directors/Procfile.base", "/app/Procfile")
end

FileUtils.mkdir("/app/.bundle")
FileUtils.cp("/app/.gap/depmgr/config.file", "/app/.bundle/config")

$stdout.sync = true

$:.unshift File.expand_path("../../lib", __FILE__)

require "language_pack"
require "language_pack/shell_helpers"

begin
  LanguagePack::Instrument.trace "compile", "app.compile" do
    if pack = LanguagePack.detect(ARGV[0], ARGV[1])
      LanguagePack::ShellHelpers.initialize_env(ARGV[2])
      pack.topic("Compiling #{pack.name}")
      pack.log("compile") do
        pack.compile
      end
    end
  end
rescue Exception => exception
  Kernel.puts " !"
  exception.message.split("\n").each do |line|
    Kernel.puts " ! #{line.strip}"
  end
  Kernel.puts " !"
  if exception.is_a?(BuildpackError)
    exit 1
  else
    raise exception
  end
end
