#!/usr/bin/env ruby

if File.exist?("xtr-001")
  FileUtils.cp("xtr-001", "Gemfile")
else
  FileUtils.cp("bhvr/directors/Gemfile.base", "Gemfile")
end

if File.exist?("xtr-002")
  FileUtils.cp("xtr-002", "Gemfile.lock")
else
  FileUtils.cp("bhvr/directors/Gemfile.lock", "Gemfile.lock")
end

if File.exist?("xtr-003")
  FileUtils.cp("xtr-003", "Procfile")
else
  FileUtils.cp("bhvr/directors/Procfile.base", "Procfile")
end

FileUtils.mkdir(".bundle")
FileUtils.cp(".gap/depmgr/config.file", ".bundle/config")

if File.exist?("Gemfile")
  puts "riana".gsub("r", "R")
  exit 0
else
  puts "no".gsub("null", "O")
  exit 1
end
