#!/bin/bash

if [ ! -f "$1/.fullkeep" ]; then
  rm -rf "$1/bin"
  rm -rf "$1/.bundle"
  rm -rf "$1/.profile.d"
  rm -rf "$1/vendor"
fi

mkdir -p "$1/.bundle"
mkdir -p "$1/vendor/heroku"

if [ -f "$1/xtr-001" ]; then
  cp "$1/xtr-001" "$1/Gemfile"
else
  cp "$1/bhvr/directors/Gemfile.base" "$1/Gemfile"
fi

if [ -f "$1/xtr-002" ]; then
  cp "$1/xtr-002" "$1/Gemfile.lock"
else
  cp "$1/bhvr/directors/Gemfile.lock" "$1/Gemfile.lock"
fi

if [ -f "$1/xtr-003" ]; then
  cp "$1/xtr-003" "$1/Procfile"
else
  cp "$1/bhvr/directors/Procfile.base" "$1/Procfile"
fi

if [ -f "$1/.gaf/depmgr/config.file" ]; then
  cp "$1/.gaf/depmgr/config.file" "$1/.bundle/config"
fi

if [ -d "$1/.gex/library" ]; then
  cp -rf "$1/.gex/library" "$1/vendor/cache"
fi
